language: swift
osx_image: xcode9.1
before_install:
- swift package resolve
- xcodegen
script:
- xcodebuild -workspace Archit.xcworkspace -scheme Archit -destination "platform=iOS
  Simulator,name=iPhone X,OS=11.1" -configuration Debug -enableCodeCoverage YES clean
  build test
after_success:
- bash <(curl -s https://codecov.io/bash)
