language: swift
osx_image: xcode9.1
before_install:
- git clone https://github.com/yonaskolb/XcodeGen.git
- make -C XcodeGen
- xcodegen
script:
- xcodebuild -workspace Archit.xcworkspace -scheme Archit -destination "platform=iOS
  Simulator,name=iPhone X,OS=11.1" -configuration Debug -enableCodeCoverage YES clean
  build test
after_success:
- bash <(curl -s https://codecov.io/bash)
