name: Archit
targets:
  Archit:
    type: application
    platform: iOS
    sources:
      - Shared
      - Archit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intelygenz.Archit
        CODE_SIGN_ENTITLEMENTS: Archit/Supporting Files/Archit.entitlements
        CLANG_WARN_ASSIGN_ENUM: true
        CLANG_WARN_IMPLICIT_SIGN_CONVERSION: true
        CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: true
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=200 -Xfrontend -warn-long-expression-type-checking=200"
      configs:
        debug:
          APS_ENVIRONMENT: development
        release:
          APS_ENVIRONMENT: production
    dependencies:
      - target: Core
      - target: Domain
    prebuildScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
        name: Swiftlint
    scheme:
      testTargets:
        - DomainTests
        - CoreTests
        - ArchitTests
        - ArchitUITests
      gatherCoverageData: true
  ArchitTests:
    type: bundle.unit-test
    platform: iOS
    sources: ArchitTests
  ArchitUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: ArchitUITests
    settings:
      TEST_TARGET_NAME: Archit
  Core:
    type: framework
    platform: iOS
    sources:
      - Shared
      - Core
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intelygenz.Archit.Core
        CLANG_WARN_ASSIGN_ENUM: true
        CLANG_WARN_IMPLICIT_SIGN_CONVERSION: true
        CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: true
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=200 -Xfrontend -warn-long-expression-type-checking=200"
    dependencies:
      - target: Domain
    scheme:
      testTargets:
        - CoreTests
      gatherCoverageData: true
  CoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: CoreTests
  Domain:
    type: framework
    platform: iOS
    sources:
      - Shared
      - Domain
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intelygenz.Archit.Domain
        CLANG_WARN_ASSIGN_ENUM: true
        CLANG_WARN_IMPLICIT_SIGN_CONVERSION: true
        CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: true
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=200 -Xfrontend -warn-long-expression-type-checking=200"
    scheme:
      testTargets:
        - DomainTests
      gatherCoverageData: true
  DomainTests:
    type: bundle.unit-test
    platform: iOS
    sources: DomainTests